# Generated by Django 3.2.5 on 2021-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_coupon_order_orderitem_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_carausel.jpg', upload_to='carausel_image')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button1_name', models.CharField(blank=True, max_length=30, null=True)),
                ('button1_link', models.CharField(blank=True, max_length=100, null=True)),
                ('button2_name', models.CharField(blank=True, max_length=30, null=True)),
                ('button2_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_testimonial.jpg', upload_to='testimonial_image')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
