# Generated by Django 3.2.5 on 2021-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carausel_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='key_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
