# Generated by Django 3.2.5 on 2021-07-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_key_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='carausel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='button1_link',
            field=models.CharField(blank=True, default='/#why-us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='button1_name',
            field=models.CharField(blank=True, default='Our Products', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='button2_link',
            field=models.CharField(blank=True, default='/#why-us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='button2_name',
            field=models.CharField(blank=True, default='Our Products', max_length=30, null=True),
        ),
    ]
