# Generated by Django 3.2.5 on 2021-07-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210715_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
