# Generated by Django 3.2.5 on 2021-07-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210721_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='item_default1.jpg', upload_to='item_pics1'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='item_default2.jpg', upload_to='item_pics2'),
        ),
        migrations.AddField(
            model_name='item',
            name='image5',
            field=models.ImageField(default='item_default1.jpg', upload_to='item_pics1'),
        ),
        migrations.AddField(
            model_name='item',
            name='image6',
            field=models.ImageField(default='item_default2.jpg', upload_to='item_pics2'),
        ),
    ]
