# Generated by Django 3.2.5 on 2021-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211205_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default_movie.jpg', upload_to='MovieImages')),
                ('is_released', models.BooleanField(default=True)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
